name: '이슈 생성'
description: 'Repo에 이슈 생성하고, 생성된 이슈는 Jira와 연동됩니다. Branch를 자동으로 생성합니다.'
labels: ["triage"]
title: '이슈 이름을 작성해주세요'
body: 
  - type: dropdown
    id: type
    attributes:
      label: 'Branch Type'
      description: '브랜치 타입을 선택하세요.'
      options:
        - feature
        - hotfix
        - release
        - test
    validations: 
      required: true

  - type: input
    id: jira_key
    attributes: 
      label: 'Jira Ticket Number'
      description: 'Jira의 이슈 키를 기입해주세요.'
      placeholder: 'ZBR-000'
    validations:
      required: true

  - type: input
    id: branch_name
    attributes:
      label: 'Branch Name'
      description: '브랜치 이름을 영어 소문자로 컨벤션에 맞게 기입해주세요.'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 'Description' 
      description: '이슈에 대해서 간략히 설명해주세요.'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes: 
      label: 'Tasks'
      description: '해당 이슈에 대해 필요한 작업 목록을 작성해주세요.'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: 'Reference'
      description: '해당 이슈와 관련된 레퍼런스를 참조해주세요'
      value: |
        - Reference1
    validations:
      required: false

  - type: markdown
    attributes: 
      value: |
        ### 브랜치 생성 방법
        - 담당자가 이슈 라벨에 `create-branch`를 추가하거나 이슈 코멘트에 `/branch`라고 입력하면 브랜치를 자동 생성합니다.
        - 브랜치 규칙: `type/JIRA-KEY-branch-name
        - Jira 키가 유효해야 생성됩니다.
